"""
Timetable filtering engine for AI part 1.

Responsibility:
- Receive timetable candidates generated by the backend.
- Apply user option conditions.
- Return up to 30 condition-passing timetables.

This module intentionally does not calculate recommendation scores or Top3.
That belongs to recommend.py in AI part 2.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


DAYS = ("월", "화", "수", "목", "금", "토", "일")


OPTION_ALIASES = {
    "current_grade": ("current_grade", "grade", "현재학년"),
    "majors": ("majors", "major", "전공"),
    "preferred_free_days": (
        "preferred_free_days",
        "preferredFreeDays",
        "선호공강요일",
    ),
    "min_credits": ("min_credits", "minCredits", "최소학점"),
    "max_credits": ("max_credits", "maxCredits", "최대학점"),
    "target_credits": ("target_credits", "targetCredits", "목표학점"),
    "include_social_service": (
        "include_social_service",
        "includeSocialService",
        "사회봉사포함",
    ),
    "required_free_days": (
        "required_free_days",
        "requiredFreeDays",
        "필수공강요일",
    ),
    "blocked_days": ("blocked_days", "blockedDays", "제외요일"),
    "max_commute_days": ("max_commute_days", "maxCommuteDays", "최대등교일수"),
    "earliest_start_time": (
        "earliest_start_time",
        "earliestStartTime",
        "최소시작시간",
    ),
    "latest_end_time": ("latest_end_time", "latestEndTime", "최대종료시간"),
}

TIMETABLE_ALIASES = {
    "timetables": ("timetables", "candidates", "timeTables", "후보", "시간표"),
    "summary": ("summary", "meta", "특징"),
    "courses": ("courses", "subjects", "classes", "과목"),
    "id": ("id", "timetable_id", "timeTableId"),
    "total_credits": ("total_credits", "totalCredits", "총학점"),
    "free_days": ("free_days", "freeDays", "공강요일"),
    "earliest_start_time": (
        "earliest_start_time",
        "earliestStartTime",
        "가장이른시작",
    ),
    "commute_days": ("commute_days", "commuteDays", "등교일수"),
    "course_name": ("name", "course_name", "subjectName", "과목명"),
    "course_credits": ("credits", "credit", "학점"),
    "course_time": ("time", "class_time", "schedule", "시간"),
    "course_category": ("category", "type", "classification", "이수구분"),
    "course_major": ("major", "department", "전공"),
}


@dataclass(frozen=True)
class FilterResult:
    passed: bool
    reasons: list[str]
    failed_reasons: list[str]
    warnings: list[str]


def _get_any(data: dict[str, Any], aliases: tuple[str, ...], default: Any = None) -> Any:
    for key in aliases:
        if key in data:
            return data[key]
    return default


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]


def _as_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in ("true", "1", "yes", "y")
    return bool(value)


def _time_to_minutes(value: Any) -> int | None:
    if value in (None, ""):
        return None
    match = re.search(r"(\d{1,2}):(\d{2})", str(value))
    if not match:
        return None
    hour = int(match.group(1))
    minute = int(match.group(2))
    return hour * 60 + minute


def _extract_days_from_time(time_value: Any) -> set[str]:
    text = str(time_value or "")
    return {day for day in DAYS if day in text}


def _extract_start_end(time_value: Any) -> tuple[int | None, int | None]:
    text = str(time_value or "")
    times = re.findall(r"(\d{1,2}:\d{2})", text)
    if not times:
        return None, None
    start = _time_to_minutes(times[0])
    end = _time_to_minutes(times[-1]) if len(times) >= 2 else None
    return start, end


def normalize_options(options: dict[str, Any] | None) -> dict[str, Any]:
    """Normalize backend/user option keys into one internal format."""
    source = options or {}

    normalized = {
        "current_grade": _get_any(source, OPTION_ALIASES["current_grade"]),
        "majors": _as_list(_get_any(source, OPTION_ALIASES["majors"])),
        "preferred_free_days": _as_list(
            _get_any(source, OPTION_ALIASES["preferred_free_days"])
        ),
        "min_credits": _get_any(source, OPTION_ALIASES["min_credits"], 0),
        "max_credits": _get_any(source, OPTION_ALIASES["max_credits"], 999),
        "target_credits": _get_any(source, OPTION_ALIASES["target_credits"]),
        "include_social_service": _as_bool(
            _get_any(source, OPTION_ALIASES["include_social_service"], True),
            default=True,
        ),
        "required_free_days": _as_list(
            _get_any(source, OPTION_ALIASES["required_free_days"])
        ),
        "blocked_days": _as_list(_get_any(source, OPTION_ALIASES["blocked_days"])),
        "max_commute_days": _get_any(source, OPTION_ALIASES["max_commute_days"]),
        "earliest_start_time": _get_any(
            source, OPTION_ALIASES["earliest_start_time"]
        ),
        "latest_end_time": _get_any(source, OPTION_ALIASES["latest_end_time"]),
    }

    normalized["min_credits"] = int(normalized["min_credits"] or 0)
    normalized["max_credits"] = int(normalized["max_credits"] or 999)
    if normalized["target_credits"] not in (None, ""):
        normalized["target_credits"] = int(normalized["target_credits"])
    if normalized["max_commute_days"] not in (None, ""):
        normalized["max_commute_days"] = int(normalized["max_commute_days"])

    return normalized


def extract_timetables(payload: Any) -> list[dict[str, Any]]:
    """Accept either a raw list or a backend response object."""
    if isinstance(payload, list):
        return payload
    if not isinstance(payload, dict):
        raise TypeError("payload must be a list or dict")
    timetables = _get_any(payload, TIMETABLE_ALIASES["timetables"])
    if not isinstance(timetables, list):
        raise ValueError("timetable list was not found in payload")
    return timetables


def get_timetable_id(timetable: dict[str, Any]) -> str:
    timetable_id = _get_any(timetable, TIMETABLE_ALIASES["id"])
    if timetable_id is None:
        raise ValueError("timetable id is missing")
    return str(timetable_id)


def get_summary(timetable: dict[str, Any]) -> dict[str, Any]:
    summary = _get_any(timetable, TIMETABLE_ALIASES["summary"], {})
    return summary if isinstance(summary, dict) else {}


def get_courses(timetable: dict[str, Any]) -> list[dict[str, Any]]:
    courses = _get_any(timetable, TIMETABLE_ALIASES["courses"], [])
    if not isinstance(courses, list):
        return []
    return [course for course in courses if isinstance(course, dict)]


def get_total_credits(timetable: dict[str, Any]) -> int:
    summary = get_summary(timetable)
    total = _get_any(summary, TIMETABLE_ALIASES["total_credits"])
    if total is not None:
        return int(total)

    total = 0
    for course in get_courses(timetable):
        credits = _get_any(course, TIMETABLE_ALIASES["course_credits"], 0)
        total += int(credits or 0)
    return total


def get_class_days(timetable: dict[str, Any]) -> set[str]:
    days: set[str] = set()
    for course in get_courses(timetable):
        time_value = _get_any(course, TIMETABLE_ALIASES["course_time"])
        days.update(_extract_days_from_time(time_value))
    return days


def get_free_days(timetable: dict[str, Any]) -> set[str]:
    summary = get_summary(timetable)
    free_days = _get_any(summary, TIMETABLE_ALIASES["free_days"])
    if free_days is not None:
        return set(str(day) for day in _as_list(free_days))
    return set(DAYS[:5]) - get_class_days(timetable)


def get_commute_days(timetable: dict[str, Any]) -> int:
    summary = get_summary(timetable)
    commute_days = _get_any(summary, TIMETABLE_ALIASES["commute_days"])
    if commute_days is not None:
        return int(commute_days)
    return len(get_class_days(timetable))


def has_time_conflict(timetable: dict[str, Any]) -> bool:
    """Detect simple same-day overlapping class ranges."""
    ranges_by_day: dict[str, list[tuple[int, int]]] = {}

    for course in get_courses(timetable):
        time_value = _get_any(course, TIMETABLE_ALIASES["course_time"])
        start, end = _extract_start_end(time_value)
        if start is None or end is None:
            continue
        for day in _extract_days_from_time(time_value):
            ranges_by_day.setdefault(day, []).append((start, end))

    for ranges in ranges_by_day.values():
        ordered = sorted(ranges)
        for index in range(1, len(ordered)):
            previous_end = ordered[index - 1][1]
            current_start = ordered[index][0]
            if current_start < previous_end:
                return True
    return False


def contains_social_service(timetable: dict[str, Any]) -> bool:
    for course in get_courses(timetable):
        name = str(_get_any(course, TIMETABLE_ALIASES["course_name"], ""))
        category = str(_get_any(course, TIMETABLE_ALIASES["course_category"], ""))
        if "사회봉사" in name or "사회봉사" in category:
            return True
    return False


def has_major_metadata(timetable: dict[str, Any]) -> bool:
    for course in get_courses(timetable):
        if _get_any(course, TIMETABLE_ALIASES["course_major"]) is not None:
            return True
    return False


def matches_selected_major(timetable: dict[str, Any], majors: list[Any]) -> bool:
    selected = [str(major) for major in majors if str(major).strip()]
    if not selected:
        return True

    for course in get_courses(timetable):
        course_major = str(_get_any(course, TIMETABLE_ALIASES["course_major"], ""))
        if any(major in course_major or course_major in major for major in selected):
            return True
    return False


def check_conditions(
    timetable: dict[str, Any],
    options: dict[str, Any],
) -> FilterResult:
    """Return pass/fail plus explainable filtering reasons."""
    reasons: list[str] = []
    failed: list[str] = []
    warnings: list[str] = []

    timetable_id = get_timetable_id(timetable)
    total_credits = get_total_credits(timetable)
    free_days = get_free_days(timetable)
    class_days = get_class_days(timetable)
    commute_days = get_commute_days(timetable)

    min_credits = options["min_credits"]
    max_credits = options["max_credits"]
    target_credits = options["target_credits"]
    if target_credits is not None and total_credits == target_credits:
        reasons.append(f"총 학점 {total_credits}학점이 목표 학점과 일치합니다.")
    elif target_credits is not None:
        difference = abs(total_credits - target_credits)
        warnings.append(
            f"총 학점 {total_credits}학점이 목표 {target_credits}학점과 {difference}학점 차이납니다."
        )

    if total_credits < min_credits:
        failed.append(f"총 학점 {total_credits}학점이 최소 {min_credits}학점보다 낮습니다.")
    elif total_credits > max_credits:
        failed.append(f"총 학점 {total_credits}학점이 최대 {max_credits}학점을 초과합니다.")
    else:
        reasons.append(f"총 학점 {total_credits}학점이 설정 범위에 맞습니다.")

    required_free_days = set(str(day) for day in options["required_free_days"])
    if required_free_days and not required_free_days.issubset(free_days):
        missing = sorted(required_free_days - free_days)
        failed.append(f"필수 공강요일 {', '.join(missing)}을 만족하지 못했습니다.")
    elif required_free_days:
        reasons.append(f"필수 공강요일 {', '.join(sorted(required_free_days))}을 만족합니다.")

    blocked_days = set(str(day) for day in options["blocked_days"])
    if blocked_days and blocked_days.intersection(class_days):
        matched = sorted(blocked_days.intersection(class_days))
        failed.append(f"제외요일 {', '.join(matched)}에 수업이 있습니다.")

    preferred_free_days = set(str(day) for day in options["preferred_free_days"])
    matched_preferred = sorted(preferred_free_days.intersection(free_days))
    if matched_preferred:
        reasons.append(f"선호 공강요일 {', '.join(matched_preferred)}을 포함합니다.")

    max_commute_days = options["max_commute_days"]
    if max_commute_days is not None and commute_days > max_commute_days:
        failed.append(f"등교일수 {commute_days}일이 최대 {max_commute_days}일을 초과합니다.")
    elif max_commute_days is not None:
        reasons.append(f"등교일수 {commute_days}일이 조건에 맞습니다.")

    earliest = _time_to_minutes(options["earliest_start_time"])
    latest = _time_to_minutes(options["latest_end_time"])
    for course in get_courses(timetable):
        time_value = _get_any(course, TIMETABLE_ALIASES["course_time"])
        start, end = _extract_start_end(time_value)
        if earliest is not None and start is not None and start < earliest:
            failed.append(f"{timetable_id}에 설정 시작시간보다 이른 수업이 있습니다.")
            break
        if latest is not None and end is not None and end > latest:
            failed.append(f"{timetable_id}에 설정 종료시간보다 늦은 수업이 있습니다.")
            break

    if not options["include_social_service"] and contains_social_service(timetable):
        warnings.append("사회봉사 과목이 포함되어 있습니다.")

    if has_time_conflict(timetable):
        failed.append("시간이 겹치는 수업이 있습니다.")

    majors = options["majors"]
    if majors and has_major_metadata(timetable):
        if matches_selected_major(timetable, majors):
            reasons.append("선택한 전공 조건과 맞는 과목을 포함합니다.")
        else:
            failed.append("선택한 전공 조건과 맞는 과목이 없습니다.")

    return FilterResult(
        passed=not failed,
        reasons=reasons,
        failed_reasons=failed,
        warnings=warnings,
    )


def filter_timetables(
    timetables: list[dict[str, Any]],
    options: dict[str, Any] | None,
    limit: int = 30,
) -> list[dict[str, Any]]:
    """Filter timetable candidates and return only AI-2-ready records."""
    normalized_options = normalize_options(options)
    passed_records: list[dict[str, Any]] = []

    for timetable in timetables:
        result = check_conditions(timetable, normalized_options)
        if not result.passed:
            continue

        passed_records.append(
            {
                "id": get_timetable_id(timetable),
                "reasons": result.reasons,
                "warnings": result.warnings,
                "timetable": timetable,
            }
        )

    if not normalized_options["include_social_service"]:
        without_social_service = [
            record
            for record in passed_records
            if not contains_social_service(record["timetable"])
        ]
        if without_social_service:
            return without_social_service[:limit]

        for record in passed_records:
            record.setdefault("warnings", []).append(
                "사회봉사 제외 조건을 만족하는 시간표가 없어 사회봉사 포함 후보를 유지했습니다."
            )

    return passed_records[:limit]


def extract_options(payload: Any) -> dict[str, Any]:
    if isinstance(payload, dict):
        options = _get_any(payload, ("options", "option", "옵션"), {})
        if isinstance(options, dict):
            return options
    return {}


def _split_input_values(value: str) -> list[str]:
    if not value.strip():
        return []
    normalized = value.replace(",", " ")
    return [item.strip() for item in normalized.split() if item.strip()]


def prompt_user_options() -> dict[str, Any]:
    """Prompt a developer/tester for user-selected options in the terminal."""
    print("사용자 선택 옵션을 입력하세요. 비워두면 해당 조건은 생략됩니다.")

    grade = input("현재학년 (예: 3): ").strip()
    majors = input("전공 (쉼표로 구분, 예: 소프트웨어공학전공,정보통신공학전공): ").strip()
    target_credits = input("목표학점 (예: 18, 범위 조건이면 Enter): ").strip()

    min_credits = ""
    max_credits = ""
    if not target_credits:
        min_credits = input("최소학점 (예: 15): ").strip()
        max_credits = input("최대학점 (예: 21): ").strip()

    preferred_free_days = input("선호공강요일 (예: 월 금 또는 금): ").strip()
    social_service = input("사회봉사 포함? (y/N): ").strip().lower()

    options: dict[str, Any] = {}
    if grade:
        options["현재학년"] = int(grade)
    if majors:
        options["전공"] = _split_input_values(majors)
    if target_credits:
        options["목표학점"] = int(target_credits)
    else:
        if min_credits:
            options["최소학점"] = int(min_credits)
        if max_credits:
            options["최대학점"] = int(max_credits)
    if preferred_free_days:
        options["선호공강요일"] = _split_input_values(preferred_free_days)

    options["사회봉사포함"] = social_service in ("y", "yes", "true", "1")
    return options


def filter_payload(payload: Any, options: dict[str, Any] | None, limit: int = 30) -> dict[str, Any]:
    if options is None:
        options = extract_options(payload)

    timetables = extract_timetables(payload)
    filtered = filter_timetables(timetables, options, limit)
    warnings = []
    normalized_options = normalize_options(options)
    if (
        filtered
        and not normalized_options["include_social_service"]
        and all(contains_social_service(record["timetable"]) for record in filtered)
    ):
        warnings.append(
            "사회봉사 제외 조건을 만족하는 시간표가 없어 사회봉사 포함 후보를 결과에 포함했습니다."
        )

    return {
        "count": len(filtered),
        "limit": limit,
        "options": options,
        "normalized_options": normalized_options,
        "warnings": warnings,
        "results": filtered,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Filter timetable candidates.")
    parser.add_argument("--input", required=False, help="Path to timetable candidates JSON.")
    parser.add_argument(
        "--options",
        required=False,
        help="Path to user options JSON. If omitted, input JSON's 옵션/options field is used.",
    )
    parser.add_argument("--output", required=False, help="Path to filtered result JSON.")
    parser.add_argument("--limit", type=int, default=30)
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Prompt for current grade, credits, free days, and social service option.",
    )
    args = parser.parse_args()

    script_dir = Path(__file__).parent
    no_cli_args = len(sys.argv) == 1

    input_path = Path(args.input) if args.input else script_dir / "filter_sample_input.json"
    output_path = Path(args.output) if args.output else script_dir / "filtered_timetables.json"

    if not input_path.is_absolute() and not input_path.exists():
        script_relative_input = script_dir / input_path
        if script_relative_input.exists():
            input_path = script_relative_input

    if not output_path.is_absolute() and output_path.parent == Path("."):
        output_path = script_dir / output_path

    payload = json.loads(input_path.read_text(encoding="utf-8"))
    options = None
    if args.interactive or no_cli_args:
        options = prompt_user_options()
    elif args.options:
        options_path = Path(args.options)
        if not options_path.is_absolute() and not options_path.exists():
            script_relative_options = script_dir / options_path
            if script_relative_options.exists():
                options_path = script_relative_options
        options = json.loads(options_path.read_text(encoding="utf-8"))
    result = filter_payload(payload, options, args.limit)
    output_path.write_text(
        json.dumps(result, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"필터링 결과를 저장했습니다: {output_path}")


if __name__ == "__main__":
    main()
